[application]
asset_dir = "assets"

[web.app]
title = "4ever & Beyond — Community Platform"

[web.resource]
style = ["/assets/tailwind.css", "/assets/main.css"]
script = []

[web.resource.dev]
style = ["/assets/tailwind.css", "/assets/main.css"]
script = []
