// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddEventQuestionArgs {
    pub event_id: u64,
    pub label: String,
    pub field_type: String,
    pub options: Option<String>,
    pub is_required: bool,
}

impl From<AddEventQuestionArgs> for super::Reducer {
    fn from(args: AddEventQuestionArgs) -> Self {
        Self::AddEventQuestion {
            event_id: args.event_id,
            label: args.label,
            field_type: args.field_type,
            options: args.options,
            is_required: args.is_required,
        }
    }
}

impl __sdk::InModule for AddEventQuestionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_event_question`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_event_question {
    /// Request that the remote module invoke the reducer `add_event_question` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_event_question:add_event_question_then`] to run a callback after the reducer completes.
    fn add_event_question(
        &self,
        event_id: u64,
        label: String,
        field_type: String,
        options: Option<String>,
        is_required: bool,
    ) -> __sdk::Result<()> {
        self.add_event_question_then(event_id, label, field_type, options, is_required, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_event_question` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_event_question_then(
        &self,
        event_id: u64,
        label: String,
        field_type: String,
        options: Option<String>,
        is_required: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_event_question for super::RemoteReducers {
    fn add_event_question_then(
        &self,
        event_id: u64,
        label: String,
        field_type: String,
        options: Option<String>,
        is_required: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddEventQuestionArgs {
                event_id,
                label,
                field_type,
                options,
                is_required,
            },
            callback,
        )
    }
}
