// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateEventArgs {
    pub title: String,
    pub description: String,
    pub event_date: String,
    pub priority: u32,
    pub passcode: String,
}

impl From<CreateEventArgs> for super::Reducer {
    fn from(args: CreateEventArgs) -> Self {
        Self::CreateEvent {
            title: args.title,
            description: args.description,
            event_date: args.event_date,
            priority: args.priority,
            passcode: args.passcode,
        }
    }
}

impl __sdk::InModule for CreateEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_event {
    /// Request that the remote module invoke the reducer `create_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_event:create_event_then`] to run a callback after the reducer completes.
    fn create_event(
        &self,
        title: String,
        description: String,
        event_date: String,
        priority: u32,
        passcode: String,
    ) -> __sdk::Result<()> {
        self.create_event_then(
            title,
            description,
            event_date,
            priority,
            passcode,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_event_then(
        &self,
        title: String,
        description: String,
        event_date: String,
        priority: u32,
        passcode: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_event for super::RemoteReducers {
    fn create_event_then(
        &self,
        title: String,
        description: String,
        event_date: String,
        priority: u32,
        passcode: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateEventArgs {
                title,
                description,
                event_date,
                priority,
                passcode,
            },
            callback,
        )
    }
}
