// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EventQuestion {
    pub id: u64,
    pub event_id: u64,
    pub label: String,
    pub field_type: String,
    pub options: Option<String>,
    pub is_required: bool,
}

impl __sdk::InModule for EventQuestion {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EventQuestion`.
///
/// Provides typed access to columns for query building.
pub struct EventQuestionCols {
    pub id: __sdk::__query_builder::Col<EventQuestion, u64>,
    pub event_id: __sdk::__query_builder::Col<EventQuestion, u64>,
    pub label: __sdk::__query_builder::Col<EventQuestion, String>,
    pub field_type: __sdk::__query_builder::Col<EventQuestion, String>,
    pub options: __sdk::__query_builder::Col<EventQuestion, Option<String>>,
    pub is_required: __sdk::__query_builder::Col<EventQuestion, bool>,
}

impl __sdk::__query_builder::HasCols for EventQuestion {
    type Cols = EventQuestionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EventQuestionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            label: __sdk::__query_builder::Col::new(table_name, "label"),
            field_type: __sdk::__query_builder::Col::new(table_name, "field_type"),
            options: __sdk::__query_builder::Col::new(table_name, "options"),
            is_required: __sdk::__query_builder::Col::new(table_name, "is_required"),
        }
    }
}

/// Indexed column accessor struct for the table `EventQuestion`.
///
/// Provides typed access to indexed columns for query building.
pub struct EventQuestionIxCols {
    pub id: __sdk::__query_builder::IxCol<EventQuestion, u64>,
}

impl __sdk::__query_builder::HasIxCols for EventQuestion {
    type IxCols = EventQuestionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EventQuestionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EventQuestion {}
