// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::event_response_type::EventResponse;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `event_response`.
///
/// Obtain a handle from the [`EventResponseTableAccess::event_response`] method on [`super::RemoteTables`],
/// like `ctx.db.event_response()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.event_response().on_insert(...)`.
pub struct EventResponseTableHandle<'ctx> {
    imp: __sdk::TableHandle<EventResponse>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `event_response`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EventResponseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EventResponseTableHandle`], which mediates access to the table `event_response`.
    fn event_response(&self) -> EventResponseTableHandle<'_>;
}

impl EventResponseTableAccess for super::RemoteTables {
    fn event_response(&self) -> EventResponseTableHandle<'_> {
        EventResponseTableHandle {
            imp: self.imp.get_table::<EventResponse>("event_response"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EventResponseInsertCallbackId(__sdk::CallbackId);
pub struct EventResponseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EventResponseTableHandle<'ctx> {
    type Row = EventResponse;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EventResponse> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EventResponseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EventResponseInsertCallbackId {
        EventResponseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EventResponseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EventResponseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EventResponseDeleteCallbackId {
        EventResponseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EventResponseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EventResponseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EventResponseTableHandle<'ctx> {
    type UpdateCallbackId = EventResponseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EventResponseUpdateCallbackId {
        EventResponseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EventResponseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `event_response`,
/// which allows point queries on the field of the same name
/// via the [`EventResponseIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.event_response().id().find(...)`.
pub struct EventResponseIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EventResponse, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EventResponseTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `event_response`.
    pub fn id(&self) -> EventResponseIdUnique<'ctx> {
        EventResponseIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EventResponseIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EventResponse> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EventResponse>("event_response");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EventResponse>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EventResponse>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EventResponse`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait event_responseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EventResponse`.
    fn event_response(&self) -> __sdk::__query_builder::Table<EventResponse>;
}

impl event_responseQueryTableAccess for __sdk::QueryTableAccessor {
    fn event_response(&self) -> __sdk::__query_builder::Table<EventResponse> {
        __sdk::__query_builder::Table::new("event_response")
    }
}
