// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Event {
    pub id: u64,
    pub title: String,
    pub description: String,
    pub event_date: String,
    pub priority: u32,
    pub is_active: bool,
    pub passcode: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for Event {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Event`.
///
/// Provides typed access to columns for query building.
pub struct EventCols {
    pub id: __sdk::__query_builder::Col<Event, u64>,
    pub title: __sdk::__query_builder::Col<Event, String>,
    pub description: __sdk::__query_builder::Col<Event, String>,
    pub event_date: __sdk::__query_builder::Col<Event, String>,
    pub priority: __sdk::__query_builder::Col<Event, u32>,
    pub is_active: __sdk::__query_builder::Col<Event, bool>,
    pub passcode: __sdk::__query_builder::Col<Event, String>,
    pub created_at: __sdk::__query_builder::Col<Event, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Event {
    type Cols = EventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            event_date: __sdk::__query_builder::Col::new(table_name, "event_date"),
            priority: __sdk::__query_builder::Col::new(table_name, "priority"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            passcode: __sdk::__query_builder::Col::new(table_name, "passcode"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Event`.
///
/// Provides typed access to indexed columns for query building.
pub struct EventIxCols {
    pub id: __sdk::__query_builder::IxCol<Event, u64>,
}

impl __sdk::__query_builder::HasIxCols for Event {
    type IxCols = EventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Event {}
