// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EventResponse {
    pub id: u64,
    pub event_id: u64,
    pub user_identity: __sdk::Identity,
    pub answers: String,
    pub submitted_at: __sdk::Timestamp,
}

impl __sdk::InModule for EventResponse {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EventResponse`.
///
/// Provides typed access to columns for query building.
pub struct EventResponseCols {
    pub id: __sdk::__query_builder::Col<EventResponse, u64>,
    pub event_id: __sdk::__query_builder::Col<EventResponse, u64>,
    pub user_identity: __sdk::__query_builder::Col<EventResponse, __sdk::Identity>,
    pub answers: __sdk::__query_builder::Col<EventResponse, String>,
    pub submitted_at: __sdk::__query_builder::Col<EventResponse, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for EventResponse {
    type Cols = EventResponseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EventResponseCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            user_identity: __sdk::__query_builder::Col::new(table_name, "user_identity"),
            answers: __sdk::__query_builder::Col::new(table_name, "answers"),
            submitted_at: __sdk::__query_builder::Col::new(table_name, "submitted_at"),
        }
    }
}

/// Indexed column accessor struct for the table `EventResponse`.
///
/// Provides typed access to indexed columns for query building.
pub struct EventResponseIxCols {
    pub id: __sdk::__query_builder::IxCol<EventResponse, u64>,
}

impl __sdk::__query_builder::HasIxCols for EventResponse {
    type IxCols = EventResponseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EventResponseIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EventResponse {}
