// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::event_question_type::EventQuestion;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `event_question`.
///
/// Obtain a handle from the [`EventQuestionTableAccess::event_question`] method on [`super::RemoteTables`],
/// like `ctx.db.event_question()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.event_question().on_insert(...)`.
pub struct EventQuestionTableHandle<'ctx> {
    imp: __sdk::TableHandle<EventQuestion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `event_question`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EventQuestionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EventQuestionTableHandle`], which mediates access to the table `event_question`.
    fn event_question(&self) -> EventQuestionTableHandle<'_>;
}

impl EventQuestionTableAccess for super::RemoteTables {
    fn event_question(&self) -> EventQuestionTableHandle<'_> {
        EventQuestionTableHandle {
            imp: self.imp.get_table::<EventQuestion>("event_question"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EventQuestionInsertCallbackId(__sdk::CallbackId);
pub struct EventQuestionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EventQuestionTableHandle<'ctx> {
    type Row = EventQuestion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EventQuestion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EventQuestionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EventQuestionInsertCallbackId {
        EventQuestionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EventQuestionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EventQuestionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EventQuestionDeleteCallbackId {
        EventQuestionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EventQuestionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EventQuestionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EventQuestionTableHandle<'ctx> {
    type UpdateCallbackId = EventQuestionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EventQuestionUpdateCallbackId {
        EventQuestionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EventQuestionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `event_question`,
/// which allows point queries on the field of the same name
/// via the [`EventQuestionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.event_question().id().find(...)`.
pub struct EventQuestionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EventQuestion, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EventQuestionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `event_question`.
    pub fn id(&self) -> EventQuestionIdUnique<'ctx> {
        EventQuestionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EventQuestionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EventQuestion> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EventQuestion>("event_question");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EventQuestion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EventQuestion>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EventQuestion`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait event_questionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EventQuestion`.
    fn event_question(&self) -> __sdk::__query_builder::Table<EventQuestion>;
}

impl event_questionQueryTableAccess for __sdk::QueryTableAccessor {
    fn event_question(&self) -> __sdk::__query_builder::Table<EventQuestion> {
        __sdk::__query_builder::Table::new("event_question")
    }
}
