// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterProfileArgs {
    pub nickname: String,
    pub entry_year: String,
    pub contact_channel: String,
    pub student_id: Option<String>,
}

impl From<RegisterProfileArgs> for super::Reducer {
    fn from(args: RegisterProfileArgs) -> Self {
        Self::RegisterProfile {
            nickname: args.nickname,
            entry_year: args.entry_year,
            contact_channel: args.contact_channel,
            student_id: args.student_id,
        }
    }
}

impl __sdk::InModule for RegisterProfileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_profile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_profile {
    /// Request that the remote module invoke the reducer `register_profile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_profile:register_profile_then`] to run a callback after the reducer completes.
    fn register_profile(
        &self,
        nickname: String,
        entry_year: String,
        contact_channel: String,
        student_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.register_profile_then(nickname, entry_year, contact_channel, student_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_profile` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_profile_then(
        &self,
        nickname: String,
        entry_year: String,
        contact_channel: String,
        student_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_profile for super::RemoteReducers {
    fn register_profile_then(
        &self,
        nickname: String,
        entry_year: String,
        contact_channel: String,
        student_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterProfileArgs {
                nickname,
                entry_year,
                contact_channel,
                student_id,
            },
            callback,
        )
    }
}
