// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitResponseArgs {
    pub event_id: u64,
    pub passcode: String,
    pub answers: String,
}

impl From<SubmitResponseArgs> for super::Reducer {
    fn from(args: SubmitResponseArgs) -> Self {
        Self::SubmitResponse {
            event_id: args.event_id,
            passcode: args.passcode,
            answers: args.answers,
        }
    }
}

impl __sdk::InModule for SubmitResponseArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_response`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_response {
    /// Request that the remote module invoke the reducer `submit_response` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_response:submit_response_then`] to run a callback after the reducer completes.
    fn submit_response(
        &self,
        event_id: u64,
        passcode: String,
        answers: String,
    ) -> __sdk::Result<()> {
        self.submit_response_then(event_id, passcode, answers, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `submit_response` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_response_then(
        &self,
        event_id: u64,
        passcode: String,
        answers: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_response for super::RemoteReducers {
    fn submit_response_then(
        &self,
        event_id: u64,
        passcode: String,
        answers: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SubmitResponseArgs {
                event_id,
                passcode,
                answers,
            },
            callback,
        )
    }
}
