// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ToggleVerificationArgs {
    pub target_identity: __sdk::Identity,
}

impl From<ToggleVerificationArgs> for super::Reducer {
    fn from(args: ToggleVerificationArgs) -> Self {
        Self::ToggleVerification {
            target_identity: args.target_identity,
        }
    }
}

impl __sdk::InModule for ToggleVerificationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `toggle_verification`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait toggle_verification {
    /// Request that the remote module invoke the reducer `toggle_verification` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`toggle_verification:toggle_verification_then`] to run a callback after the reducer completes.
    fn toggle_verification(&self, target_identity: __sdk::Identity) -> __sdk::Result<()> {
        self.toggle_verification_then(target_identity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `toggle_verification` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn toggle_verification_then(
        &self,
        target_identity: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl toggle_verification for super::RemoteReducers {
    fn toggle_verification_then(
        &self,
        target_identity: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ToggleVerificationArgs { target_identity }, callback)
    }
}
